apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::553866869951:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1ESYMTP54SY0U
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::553866869951:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []

kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-16T07:32:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1833"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c19c8ed1-d653-4db6-b77f-db44bf39ed6b
